/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _rootNetlifyRouteImport } from './routes/__root.netlify'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SymptomCheckerRouteImport } from './routes/symptom-checker'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as NpRouteImport } from './routes/np'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookRouteImport } from './routes/book'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocationsIndexRouteImport } from './routes/locations.index'
import { Route as ParentVaccinationsRouteImport } from './routes/parent.vaccinations'
import { Route as ParentSettingsRouteImport } from './routes/parent.settings'
import { Route as ParentGrowthRouteImport } from './routes/parent.growth'
import { Route as ParentDocumentsRouteImport } from './routes/parent.documents'
import { Route as ParentDashboardRouteImport } from './routes/parent.dashboard'
import { Route as ParentChildrenRouteImport } from './routes/parent.children'
import { Route as ParentAppointmentsRouteImport } from './routes/parent.appointments'
import { Route as NpStatsRouteImport } from './routes/np.stats'
import { Route as NpSettingsRouteImport } from './routes/np.settings'
import { Route as NpScheduleRouteImport } from './routes/np.schedule'
import { Route as NpPatientRouteImport } from './routes/np.patient'
import { Route as LocationsCityRouteImport } from './routes/locations.$city'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRevenueRouteImport } from './routes/admin.revenue'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminProvidersRouteImport } from './routes/admin.providers'
import { Route as AdminInsightsRouteImport } from './routes/admin.insights'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAppointmentsRouteImport } from './routes/admin.appointments'
import { Route as NpDocumentVisitIdRouteImport } from './routes/np.document.$visitId'

const _rootNetlifyRoute = _rootNetlifyRouteImport.update({
  id: '/__root/netlify',
  path: '/netlify',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SymptomCheckerRoute = SymptomCheckerRouteImport.update({
  id: '/symptom-checker',
  path: '/symptom-checker',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const NpRoute = NpRouteImport.update({
  id: '/np',
  path: '/np',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentVaccinationsRoute = ParentVaccinationsRouteImport.update({
  id: '/vaccinations',
  path: '/vaccinations',
  getParentRoute: () => ParentRoute,
} as any)
const ParentSettingsRoute = ParentSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ParentRoute,
} as any)
const ParentGrowthRoute = ParentGrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => ParentRoute,
} as any)
const ParentDocumentsRoute = ParentDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => ParentRoute,
} as any)
const ParentDashboardRoute = ParentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ParentRoute,
} as any)
const ParentChildrenRoute = ParentChildrenRouteImport.update({
  id: '/children',
  path: '/children',
  getParentRoute: () => ParentRoute,
} as any)
const ParentAppointmentsRoute = ParentAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => ParentRoute,
} as any)
const NpStatsRoute = NpStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => NpRoute,
} as any)
const NpSettingsRoute = NpSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => NpRoute,
} as any)
const NpScheduleRoute = NpScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => NpRoute,
} as any)
const NpPatientRoute = NpPatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => NpRoute,
} as any)
const LocationsCityRoute = LocationsCityRouteImport.update({
  id: '/locations/$city',
  path: '/locations/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRevenueRoute = AdminRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProvidersRoute = AdminProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInsightsRoute = AdminInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAppointmentsRoute = AdminAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AdminRoute,
} as any)
const NpDocumentVisitIdRoute = NpDocumentVisitIdRouteImport.update({
  id: '/document/$visitId',
  path: '/document/$visitId',
  getParentRoute: () => NpRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/np': typeof NpRouteWithChildren
  '/parent': typeof ParentRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/providers': typeof ProvidersRoute
  '/services': typeof ServicesRoute
  '/symptom-checker': typeof SymptomCheckerRoute
  '/terms': typeof TermsRoute
  '/netlify': typeof _rootNetlifyRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/insights': typeof AdminInsightsRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/locations/$city': typeof LocationsCityRoute
  '/np/patient': typeof NpPatientRoute
  '/np/schedule': typeof NpScheduleRoute
  '/np/settings': typeof NpSettingsRoute
  '/np/stats': typeof NpStatsRoute
  '/parent/appointments': typeof ParentAppointmentsRoute
  '/parent/children': typeof ParentChildrenRoute
  '/parent/dashboard': typeof ParentDashboardRoute
  '/parent/documents': typeof ParentDocumentsRoute
  '/parent/growth': typeof ParentGrowthRoute
  '/parent/settings': typeof ParentSettingsRoute
  '/parent/vaccinations': typeof ParentVaccinationsRoute
  '/locations/': typeof LocationsIndexRoute
  '/np/document/$visitId': typeof NpDocumentVisitIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/np': typeof NpRouteWithChildren
  '/parent': typeof ParentRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/providers': typeof ProvidersRoute
  '/services': typeof ServicesRoute
  '/symptom-checker': typeof SymptomCheckerRoute
  '/terms': typeof TermsRoute
  '/netlify': typeof _rootNetlifyRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/insights': typeof AdminInsightsRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/locations/$city': typeof LocationsCityRoute
  '/np/patient': typeof NpPatientRoute
  '/np/schedule': typeof NpScheduleRoute
  '/np/settings': typeof NpSettingsRoute
  '/np/stats': typeof NpStatsRoute
  '/parent/appointments': typeof ParentAppointmentsRoute
  '/parent/children': typeof ParentChildrenRoute
  '/parent/dashboard': typeof ParentDashboardRoute
  '/parent/documents': typeof ParentDocumentsRoute
  '/parent/growth': typeof ParentGrowthRoute
  '/parent/settings': typeof ParentSettingsRoute
  '/parent/vaccinations': typeof ParentVaccinationsRoute
  '/locations': typeof LocationsIndexRoute
  '/np/document/$visitId': typeof NpDocumentVisitIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/np': typeof NpRouteWithChildren
  '/parent': typeof ParentRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/providers': typeof ProvidersRoute
  '/services': typeof ServicesRoute
  '/symptom-checker': typeof SymptomCheckerRoute
  '/terms': typeof TermsRoute
  '/__root/netlify': typeof _rootNetlifyRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/insights': typeof AdminInsightsRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/locations/$city': typeof LocationsCityRoute
  '/np/patient': typeof NpPatientRoute
  '/np/schedule': typeof NpScheduleRoute
  '/np/settings': typeof NpSettingsRoute
  '/np/stats': typeof NpStatsRoute
  '/parent/appointments': typeof ParentAppointmentsRoute
  '/parent/children': typeof ParentChildrenRoute
  '/parent/dashboard': typeof ParentDashboardRoute
  '/parent/documents': typeof ParentDocumentsRoute
  '/parent/growth': typeof ParentGrowthRoute
  '/parent/settings': typeof ParentSettingsRoute
  '/parent/vaccinations': typeof ParentVaccinationsRoute
  '/locations/': typeof LocationsIndexRoute
  '/np/document/$visitId': typeof NpDocumentVisitIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/book'
    | '/contact'
    | '/login'
    | '/np'
    | '/parent'
    | '/privacy'
    | '/providers'
    | '/services'
    | '/symptom-checker'
    | '/terms'
    | '/netlify'
    | '/admin/appointments'
    | '/admin/audit'
    | '/admin/dashboard'
    | '/admin/insights'
    | '/admin/providers'
    | '/admin/reports'
    | '/admin/revenue'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/locations/$city'
    | '/np/patient'
    | '/np/schedule'
    | '/np/settings'
    | '/np/stats'
    | '/parent/appointments'
    | '/parent/children'
    | '/parent/dashboard'
    | '/parent/documents'
    | '/parent/growth'
    | '/parent/settings'
    | '/parent/vaccinations'
    | '/locations/'
    | '/np/document/$visitId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/book'
    | '/contact'
    | '/login'
    | '/np'
    | '/parent'
    | '/privacy'
    | '/providers'
    | '/services'
    | '/symptom-checker'
    | '/terms'
    | '/netlify'
    | '/admin/appointments'
    | '/admin/audit'
    | '/admin/dashboard'
    | '/admin/insights'
    | '/admin/providers'
    | '/admin/reports'
    | '/admin/revenue'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/locations/$city'
    | '/np/patient'
    | '/np/schedule'
    | '/np/settings'
    | '/np/stats'
    | '/parent/appointments'
    | '/parent/children'
    | '/parent/dashboard'
    | '/parent/documents'
    | '/parent/growth'
    | '/parent/settings'
    | '/parent/vaccinations'
    | '/locations'
    | '/np/document/$visitId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/book'
    | '/contact'
    | '/login'
    | '/np'
    | '/parent'
    | '/privacy'
    | '/providers'
    | '/services'
    | '/symptom-checker'
    | '/terms'
    | '/__root/netlify'
    | '/admin/appointments'
    | '/admin/audit'
    | '/admin/dashboard'
    | '/admin/insights'
    | '/admin/providers'
    | '/admin/reports'
    | '/admin/revenue'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/locations/$city'
    | '/np/patient'
    | '/np/schedule'
    | '/np/settings'
    | '/np/stats'
    | '/parent/appointments'
    | '/parent/children'
    | '/parent/dashboard'
    | '/parent/documents'
    | '/parent/growth'
    | '/parent/settings'
    | '/parent/vaccinations'
    | '/locations/'
    | '/np/document/$visitId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRoute
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  NpRoute: typeof NpRouteWithChildren
  ParentRoute: typeof ParentRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ProvidersRoute: typeof ProvidersRoute
  ServicesRoute: typeof ServicesRoute
  SymptomCheckerRoute: typeof SymptomCheckerRoute
  TermsRoute: typeof TermsRoute
  _rootNetlifyRoute: typeof _rootNetlifyRoute
  LocationsCityRoute: typeof LocationsCityRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__root/netlify': {
      id: '/__root/netlify'
      path: '/netlify'
      fullPath: '/netlify'
      preLoaderRoute: typeof _rootNetlifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/symptom-checker': {
      id: '/symptom-checker'
      path: '/symptom-checker'
      fullPath: '/symptom-checker'
      preLoaderRoute: typeof SymptomCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/np': {
      id: '/np'
      path: '/np'
      fullPath: '/np'
      preLoaderRoute: typeof NpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/vaccinations': {
      id: '/parent/vaccinations'
      path: '/vaccinations'
      fullPath: '/parent/vaccinations'
      preLoaderRoute: typeof ParentVaccinationsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/settings': {
      id: '/parent/settings'
      path: '/settings'
      fullPath: '/parent/settings'
      preLoaderRoute: typeof ParentSettingsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/growth': {
      id: '/parent/growth'
      path: '/growth'
      fullPath: '/parent/growth'
      preLoaderRoute: typeof ParentGrowthRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/documents': {
      id: '/parent/documents'
      path: '/documents'
      fullPath: '/parent/documents'
      preLoaderRoute: typeof ParentDocumentsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/dashboard': {
      id: '/parent/dashboard'
      path: '/dashboard'
      fullPath: '/parent/dashboard'
      preLoaderRoute: typeof ParentDashboardRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/children': {
      id: '/parent/children'
      path: '/children'
      fullPath: '/parent/children'
      preLoaderRoute: typeof ParentChildrenRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/appointments': {
      id: '/parent/appointments'
      path: '/appointments'
      fullPath: '/parent/appointments'
      preLoaderRoute: typeof ParentAppointmentsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/np/stats': {
      id: '/np/stats'
      path: '/stats'
      fullPath: '/np/stats'
      preLoaderRoute: typeof NpStatsRouteImport
      parentRoute: typeof NpRoute
    }
    '/np/settings': {
      id: '/np/settings'
      path: '/settings'
      fullPath: '/np/settings'
      preLoaderRoute: typeof NpSettingsRouteImport
      parentRoute: typeof NpRoute
    }
    '/np/schedule': {
      id: '/np/schedule'
      path: '/schedule'
      fullPath: '/np/schedule'
      preLoaderRoute: typeof NpScheduleRouteImport
      parentRoute: typeof NpRoute
    }
    '/np/patient': {
      id: '/np/patient'
      path: '/patient'
      fullPath: '/np/patient'
      preLoaderRoute: typeof NpPatientRouteImport
      parentRoute: typeof NpRoute
    }
    '/locations/$city': {
      id: '/locations/$city'
      path: '/locations/$city'
      fullPath: '/locations/$city'
      preLoaderRoute: typeof LocationsCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/revenue': {
      id: '/admin/revenue'
      path: '/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AdminRevenueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/providers': {
      id: '/admin/providers'
      path: '/providers'
      fullPath: '/admin/providers'
      preLoaderRoute: typeof AdminProvidersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/insights': {
      id: '/admin/insights'
      path: '/insights'
      fullPath: '/admin/insights'
      preLoaderRoute: typeof AdminInsightsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/appointments': {
      id: '/admin/appointments'
      path: '/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AdminAppointmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/np/document/$visitId': {
      id: '/np/document/$visitId'
      path: '/document/$visitId'
      fullPath: '/np/document/$visitId'
      preLoaderRoute: typeof NpDocumentVisitIdRouteImport
      parentRoute: typeof NpRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAppointmentsRoute: typeof AdminAppointmentsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminInsightsRoute: typeof AdminInsightsRoute
  AdminProvidersRoute: typeof AdminProvidersRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRevenueRoute: typeof AdminRevenueRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAppointmentsRoute: AdminAppointmentsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminInsightsRoute: AdminInsightsRoute,
  AdminProvidersRoute: AdminProvidersRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRevenueRoute: AdminRevenueRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface NpRouteChildren {
  NpPatientRoute: typeof NpPatientRoute
  NpScheduleRoute: typeof NpScheduleRoute
  NpSettingsRoute: typeof NpSettingsRoute
  NpStatsRoute: typeof NpStatsRoute
  NpDocumentVisitIdRoute: typeof NpDocumentVisitIdRoute
}

const NpRouteChildren: NpRouteChildren = {
  NpPatientRoute: NpPatientRoute,
  NpScheduleRoute: NpScheduleRoute,
  NpSettingsRoute: NpSettingsRoute,
  NpStatsRoute: NpStatsRoute,
  NpDocumentVisitIdRoute: NpDocumentVisitIdRoute,
}

const NpRouteWithChildren = NpRoute._addFileChildren(NpRouteChildren)

interface ParentRouteChildren {
  ParentAppointmentsRoute: typeof ParentAppointmentsRoute
  ParentChildrenRoute: typeof ParentChildrenRoute
  ParentDashboardRoute: typeof ParentDashboardRoute
  ParentDocumentsRoute: typeof ParentDocumentsRoute
  ParentGrowthRoute: typeof ParentGrowthRoute
  ParentSettingsRoute: typeof ParentSettingsRoute
  ParentVaccinationsRoute: typeof ParentVaccinationsRoute
}

const ParentRouteChildren: ParentRouteChildren = {
  ParentAppointmentsRoute: ParentAppointmentsRoute,
  ParentChildrenRoute: ParentChildrenRoute,
  ParentDashboardRoute: ParentDashboardRoute,
  ParentDocumentsRoute: ParentDocumentsRoute,
  ParentGrowthRoute: ParentGrowthRoute,
  ParentSettingsRoute: ParentSettingsRoute,
  ParentVaccinationsRoute: ParentVaccinationsRoute,
}

const ParentRouteWithChildren =
  ParentRoute._addFileChildren(ParentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRoute,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  NpRoute: NpRouteWithChildren,
  ParentRoute: ParentRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ProvidersRoute: ProvidersRoute,
  ServicesRoute: ServicesRoute,
  SymptomCheckerRoute: SymptomCheckerRoute,
  TermsRoute: TermsRoute,
  _rootNetlifyRoute: _rootNetlifyRoute,
  LocationsCityRoute: LocationsCityRoute,
  LocationsIndexRoute: LocationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
